services:
  chromadb:
    image: chromadb/chroma:latest
    expose:
      - "8000"
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
  ollama:
    build:
      context: ./src
      dockerfile: ollamaDockerfile
    expose:
      - "11434"
    volumes:
      - ollama-models:/root/.ollama
      - ollaa-adapters:/adapters
    restart: unless-stopped
volumes:
  chroma-data:
  ollama-models:
  ollama-adapters: