services:
  chromadb:
    image: chromadb/chroma:latest
    expose:
      - "8000"
    volumes:
      - chroma-data:/chroma/chroma
    restart: unless-stopped
  ollama:
    build:
      context: ./src
      dockerfile: ollamaDockerfile
    expose:
      - "11434"
    volumes:
      - ollama-models:/root/.ollama
      - ollaa-adapters:/app/model_adapter
    restart: unless-stopped
  ai-service:
    build:
      context: ./src
      dockerfile: aiDockerfile
    expose: 
      - "8001"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - CHROMA_URL=http://chromadb:8001
      - FINNHUB_AP_KEY=${FINNHUB_AP_KEY}
    depends_on:
      - ollama
      - chromadb
    restart: unless-stopped
  
  backend:
    build:
      context: ./src/controller
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - DB_PATH=${DB_PATH}
      - DATA_PATH=${DATA_PATH}
    volumes:
      - ./src/databse:/data
    depends_on:
      - ai-service
    restart: unless-stopped
volumes:
  chroma-data:
  ollama-models:
  ollama-adapters: