name: Green Pulse CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up python
      uses: actions/setup-python@v5
     
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/green-pulse
            git pull origin main

            cat > .env << 'EOF'
            FINNHUB_API_KEY=${{ secrets.FINNHUB_API_KEY }}
            supaDBpass=${{ secrets.SUPADBPASS }}
            database=${{ secrets.DATABASE }}
            supaDBhost=${{ secrets.SUPADBHOST }}
            supaDBport=${{ secrets.SUPADBPORT }}
            EOF

            docker compose up --build -d

            docker image prune -f